apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "scalarlm.vllmname" . }}
spec:
  replicas: {{ .Values.inference_gpus }}
  selector:
    matchLabels:
      {{- include "scalarlm.vllmlabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "scalarlm.vllmlabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/app/cray/scripts/start_vllm_server.sh"]
          ports:
            - name: http
              containerPort: 8000
              hostPort: 8000
              protocol: TCP
          volumeMounts:
          {{- range .Values.volumes }}
            - name: {{ .name }}
              mountPath: {{ .path }}
          {{- end }}
            - name: cray-config
              mountPath: /app/cray/cray-config.yaml
              subPath: cray-config.yaml
          resources:
            limits:
              amd.com/gpu: 1
      volumes:
        - name: cray-config
          configMap:
            name: {{ .Release.Name }}-configmap
      {{- range .Values.volumes }}
        - name: {{ .name }}
          hostPath:
            path: {{ .hostPath }}
      {{- end }}

