image:
  repository: sudnya/scalarlm-rocm #tensorwave/scalarlm-amd
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  api_port: 9000
  vllm_port: 9001
  externalIP: 64.139.222.101

jobs_pvc:
  storageClass: local-path
  size: 100Gi

cache_pvc:
  storageClass: local-path
  size: 32Gi

model: meta-llama/Llama-3.1-8B-Instruct
max_model_length: 4096
gpu_memory_utilization: 0.95

training_gpus: 1
inference_gpus: 1

max_train_time: 86400
